### ISSUE TITLE
[Epic] Pulumi-EKS: Update pulumi-aws to v6

### ISSUE THREAD

**Issue by mnlumi** [pulumi/pulumi-eks#902]
Update pulumi-aws to V6

```[tasklist]
### Tasks
- [ ] [Update internal dependencies and examples within provider](https://github.com/pulumi/pulumi-eks/pull/910)
- [ ] [Add upgrade tests](https://github.com/pulumi/pulumi-eks/issues/927)
- [ ] https://github.com/pulumi/examples/issues/1517
- [ ] [Update pulumi-templates](https://github.com/pulumi/templates/pull/650)
```
